<?php

namespace Database\Seeders;

use App\Models\Tag;
use Illuminate\Database\Seeder;

class TagSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now();
        Tag::query()->insert([
            //brands
            ['name' => 'AA Drink', 'slug' => 'aadrink', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Acadia', 'slug' => 'acadia', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Adidas', 'slug' => 'adidas', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'AlbertHeijn', 'slug' => 'albertheijn', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Aldi', 'slug' => 'aldi', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Amazon', 'slug' => 'amazon', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Amstel', 'slug' => 'amstel', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Anheuser-Busch', 'slug' => 'anheuser_busch', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Apple', 'slug' => 'apple', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Applegreen', 'slug' => 'applegreen', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Asahi', 'slug' => 'asahi', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Avoca', 'slug' => 'avoca', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Bacardi', 'slug' => 'bacardi', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ballygowan', 'slug' => 'ballygowan', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Bewleys', 'slug' => 'bewleys', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Brambles', 'slug' => 'brambles', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Budweiser', 'slug' => 'budweiser', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Bulmers', 'slug' => 'bulmers', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Bullit', 'slug' => 'bullit', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Burger King', 'slug' => 'burgerking', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Butlers', 'slug' => 'butlers', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Cadburys', 'slug' => 'cadburys', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Cafe Nero', 'slug' => 'cafenero', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Calanda', 'slug' => 'calanda', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Camel', 'slug' => 'camel', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Capri Sun', 'slug' => 'caprisun', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Carlsberg', 'slug' => 'carlsberg', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Centra', 'slug' => 'centra', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Circle K', 'slug' => 'circlek', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Coca-Cola', 'slug' => 'coke', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Coles', 'slug' => 'coles', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Colgate', 'slug' => 'colgate', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Corona', 'slug' => 'corona', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Costa', 'slug' => 'costa', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doritos', 'slug' => 'doritos', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'DrPepper', 'slug' => 'drpepper', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Dunnes', 'slug' => 'dunnes', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Duracell', 'slug' => 'duracell', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Durex', 'slug' => 'durex', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Esquires', 'slug' => 'esquires', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Evian', 'slug' => 'evian', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Fanta', 'slug' => 'fanta', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Fernandes', 'slug' => 'fernandes', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Fosters', 'slug' => 'fosters', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Frank-and-Honest', 'slug' => 'frank_and_honest', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Frito-Lay', 'slug' => 'fritolay', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Gatorade', 'slug' => 'gatorade', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Gillette', 'slug' => 'gillette', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Golden Power', 'slug' => 'goldenpower', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Guinness', 'slug' => 'guinness', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Haribo', 'slug' => 'haribo', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Heineken', 'slug' => 'heineken', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Hertog Jan', 'slug' => 'hertog_jan', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Insomnia', 'slug' => 'insomnia', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Kellogs', 'slug' => 'kellogs', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'KFC', 'slug' => 'kfc', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Lavish', 'slug' => 'lavish', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Lego', 'slug' => 'lego', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Lidl', 'slug' => 'lidl', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Lindenvillage', 'slug' => 'lindenvillage', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Lipton', 'slug' => 'lipton', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Lolly-and-Cookes', 'slug' => 'lolly_and_cookes', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Loreal', 'slug' => 'loreal', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Lucozade', 'slug' => 'lucozade', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marlboro', 'slug' => 'marlboro', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mars', 'slug' => 'mars', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'McDonalds', 'slug' => 'mcdonalds', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Modelo', 'slug' => 'modelo', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Molson Coors', 'slug' => 'molson_coors', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Monster', 'slug' => 'monster', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Nero', 'slug' => 'nero', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Nescafe', 'slug' => 'nescafe', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Nestle', 'slug' => 'nestle', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Nike', 'slug' => 'nike', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'O-Briens', 'slug' => 'obriens', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'OK.', 'slug' => 'ok_', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Pepsi', 'slug' => 'pepsi', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Powerade', 'slug' => 'powerade', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Red Bull', 'slug' => 'redbull', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ribena', 'slug' => 'ribena', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Sainsburys', 'slug' => 'sainsburys', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Samsung', 'slug' => 'samsung', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Schutters', 'slug' => 'schutters', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '7-Eleven', 'slug' => 'seven_eleven', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Slammers', 'slug' => 'slammers', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'SPA', 'slug' => 'spa', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Spar', 'slug' => 'spar', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Starbucks', 'slug' => 'starbucks', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Stella', 'slug' => 'stella', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Subway', 'slug' => 'subway', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Supermacs', 'slug' => 'supermacs', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Supervalu', 'slug' => 'supervalu', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Tayto', 'slug' => 'tayto', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Tesco', 'slug' => 'tesco', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Tim Hortons', 'slug' => 'tim_hortons', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Thins', 'slug' => 'thins', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Volvic', 'slug' => 'volvic', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Waitrose', 'slug' => 'waitrose', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Walkers', 'slug' => 'walkers', 'created_at' => $now, 'updated_at' => $now],
            ['name' => "Wendy's", 'slug' => 'wendys', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Wilde-and-Greene', 'slug' => 'wilde_and_greene', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Winston', 'slug' => 'winston', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Woolworths', 'slug' => 'woolworths', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Wrigley', 'slug' => 'wrigleys', 'created_at' => $now, 'updated_at' => $now],

            //materials
            ['name' => 'Aluminium', 'slug' => 'aluminium', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Bronze', 'slug' => 'bronze', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Carbon Fiber', 'slug' => 'carbon_fiber', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ceramic', 'slug' => 'ceramic', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Composite', 'slug' => 'composite', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Concrete', 'slug' => 'concrete', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Copper', 'slug' => 'copper', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Fiberglass', 'slug' => 'fiberglass', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Glass', 'slug' => 'glass', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Iron or Steel', 'slug' => 'iron_or_steel', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Latex', 'slug' => 'latex', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Metal', 'slug' => 'metal', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Nickel', 'slug' => 'nickel', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Nylon', 'slug' => 'nylon', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Paper', 'slug' => 'paper', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Plastic', 'slug' => 'plastic', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Polyethylene', 'slug' => 'polyethylene', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Polymer', 'slug' => 'polymer', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Polypropylene', 'slug' => 'polypropylene', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Polystyrene', 'slug' => 'polystyrene', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'PVC', 'slug' => 'pvc', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Rubber', 'slug' => 'rubber', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Titanium', 'slug' => 'titanium', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Wood', 'slug' => 'wood', 'created_at' => $now, 'updated_at' => $now],

        ]);
    }
}
